/*  ................................Abort Module...........................*/

void end()
{
	system("cls");
	printf("\n\n\n\n\n\n\t\t\t     ......| Proprofs |......\n");
	printf("\n\t\t      ____________________________________");
	printf("\n\n\t\t\t Build By : \n\t\t\t\t     Mayank Mishra");
	printf("\n\n\t\t\t Email @ \n\t\t\t       mayank1996.skb@gmail.com");
	printf("\n\n\t\t      ____________________________________");
	printf("\n\n\t\t                   ");
	for(int i=0;i<10;i++)
	{
		printf(".");
		delay(200);
	}
	exit(0);
}